services:
  - type: web
    name: telegram-text-bot
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
