services:
  - type: web
    name: telegram-text-bot
    env: static
    autoDeploy: true
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/telegram_bot
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
